/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package spdvi;

/**
 *
 * @author Alumne
 */
public class TestGUIComponentsForm extends javax.swing.JFrame {

    /**
     * Creates new form TestGUIComponentsForm
     */
    public TestGUIComponentsForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGroupColors = new javax.swing.ButtonGroup();
        lblSaludo = new javax.swing.JLabel();
        btnClick = new javax.swing.JButton();
        txtIntroducirTexto = new javax.swing.JTextField();
        btnIntro = new javax.swing.JButton();
        lblTextoIntroducido = new javax.swing.JLabel();
        chkDriverLicense = new javax.swing.JCheckBox();
        radRed = new javax.swing.JRadioButton();
        radGreen = new javax.swing.JRadioButton();
        radBlue = new javax.swing.JRadioButton();
        bntColors = new javax.swing.JButton();
        lblColor = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("GUI Components Form");

        lblSaludo.setText("Hello Wolrd!!");
        lblSaludo.setToolTipText("This is a tooltip test.");

        btnClick.setText("Click me!");
        btnClick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClickActionPerformed(evt);
            }
        });

        txtIntroducirTexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIntroducirTextoActionPerformed(evt);
            }
        });

        btnIntro.setText("Intro");
        btnIntro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIntroActionPerformed(evt);
            }
        });

        lblTextoIntroducido.setText("jLabel1");

        chkDriverLicense.setText("Driver License");
        chkDriverLicense.setToolTipText("");
        chkDriverLicense.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                chkDriverLicenseStateChanged(evt);
            }
        });

        btnGroupColors.add(radRed);
        radRed.setText("Red");
        radRed.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radRedActionPerformed(evt);
            }
        });

        btnGroupColors.add(radGreen);
        radGreen.setSelected(true);
        radGreen.setText("Green");

        btnGroupColors.add(radBlue);
        radBlue.setText("Blue");

        bntColors.setText("Select");
        bntColors.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntColorsActionPerformed(evt);
            }
        });

        lblColor.setText("Se ha seleccionado el color:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblSaludo)
                    .addComponent(btnClick, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chkDriverLicense, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(radRed, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtIntroducirTexto, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radGreen, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radBlue, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblColor)
                            .addComponent(bntColors, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnIntro, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblTextoIntroducido)))))
                .addContainerGap(93, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblSaludo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnClick)
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtIntroducirTexto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnIntro)
                    .addComponent(lblTextoIntroducido, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(chkDriverLicense)
                .addGap(34, 34, 34)
                .addComponent(radRed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radGreen)
                    .addComponent(bntColors))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radBlue)
                    .addComponent(lblColor))
                .addContainerGap(35, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnClickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClickActionPerformed
        lblSaludo.setText("Hello with the button");
    }//GEN-LAST:event_btnClickActionPerformed

    private void btnIntroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIntroActionPerformed
        if (chkDriverLicense.isSelected())lblTextoIntroducido.setText("Has a driver license");
        else lblTextoIntroducido.setText("Hasn't a driver license");
    }//GEN-LAST:event_btnIntroActionPerformed

    private void txtIntroducirTextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIntroducirTextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIntroducirTextoActionPerformed

    private void chkDriverLicenseStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_chkDriverLicenseStateChanged
        // TODO add your handling code here:
    }//GEN-LAST:event_chkDriverLicenseStateChanged

    private void radRedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radRedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radRedActionPerformed

    private void bntColorsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntColorsActionPerformed
        if (radRed.isSelected()) lblColor.setText("Se ha seleccionado el color Red");
        else if (radGreen.isSelected()) lblColor.setText("Se ha seleccionado el color Green");
        else if (radBlue.isSelected()) lblColor.setText("Se ha seleccionado el color Blue");
    }//GEN-LAST:event_bntColorsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestGUIComponentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestGUIComponentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestGUIComponentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestGUIComponentsForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestGUIComponentsForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntColors;
    private javax.swing.JButton btnClick;
    private javax.swing.ButtonGroup btnGroupColors;
    private javax.swing.JButton btnIntro;
    private javax.swing.JCheckBox chkDriverLicense;
    private javax.swing.JLabel lblColor;
    private javax.swing.JLabel lblSaludo;
    private javax.swing.JLabel lblTextoIntroducido;
    private javax.swing.JRadioButton radBlue;
    private javax.swing.JRadioButton radGreen;
    private javax.swing.JRadioButton radRed;
    private javax.swing.JTextField txtIntroducirTexto;
    // End of variables declaration//GEN-END:variables
}
